### ISSUE TITLE
Browserify Support

### ISSUE THREAD

**Issue by kevinbeaty** [kriskowal/asap#50]
I'm trying to figure out how to bundle the browser version when requiring and bundling `asap` from another module.  It seems that simply `require("asap")` bundles the node version in the browserify bundle.

I might be missing something trivial, if so, please let me know.

Edit:

It also works if I modify `package.json` in asap to qualify the `browser*js` files in the `browser` section.  This seems to be the better option as it requires no change to the `package.json` in the requiring module.

```javascript
  "main": "./asap.js",
  "browser": {
    "./asap.js": "./browser-asap.js",
    "./raw.js": "./browser-raw.js",
    "test/domain": "./test/browser-domain.js"
  },
```
/Edit

It does seem to work if I do the following in package.json in my module that requires `asap`:

```javascript
"browser": {
   "asap": "asap/browser-asap"
}
```
and also manually modifying `browser-asap.js`  in the `asap` module to require `browser-raw`

```javascript
var var rawAsap = require("./browser-raw");
```
Thanks.

**Comment by AgentME** [comment]
Probably related: https://github.com/substack/node-browserify/issues/1119

**Comment by AgentME** [comment]
I published the `asap-browser` package to NPM to work around this issue. It's the same as asap with kevinbeaty's changes applied (main is now browser-asap.js, and browser-asap.js requires browser-raw).

**Comment by kriskowal** [comment]
@AgentME Note above that I committed and published fixes for Browserify. Please confirm that these were not sufficient.

**Comment by AgentME** [comment]
Your changes in ASAP did not fix the issue for me. I've been getting inconsistent behavior from Browserify, so I think it's a Browserify bug. I've seen the following combinations of things end up in the browserified bundle: asap.js and browser-raw.js, browser-asap.js and raw.js, and asap.js and raw.js.

**Comment by ewie** [comment]
The problem also occurs with webpack.
Modifying `package.json` as pointed out by @kevinbeaty solves it for me.
```json
"browser": {
  "./asap.js": "./browser-asap.js",
  "./raw.js": "./browser-raw.js",
  "test/domain.js": "./test/browser-domain.js"
}
```
I don't know if the `browser` field is properly defined somewhere.
The only source I could find is https://gist.github.com/defunctzombie/4339901/49493836fb873ddaa4b8a7aa0ef2352119f69211#replace-specific-files---advanced which shows that the keys under the `browser` field should be relative paths apparently _including the file extension_.

**Comment by kriskowal** [comment]
@ewie. Sending a fix up now.

**Comment by ewie** [comment]
@kriskowal. Damn you're quick :smile:. I was just preparing a PR.

**Comment by kriskowal** [comment]
I do my github gardening on Saturdays. I’ve pushed a patch release. I verified locally that it works with Browserify, but as always, mileage will vary. Please let me know if there are further problems.

**Comment by ewie** [comment]
@kriskowal. I guess you mean release 2.0.1. That doesn't solve the problem for webpack. As I wrote in my first comment you probably have to specify the `browser` field in terms of relative file paths (including the file extensions which are missing from the keys in 588bb88).

**Comment by kriskowal** [comment]
@ewie I mean 2.0.2, which I forgot to push. Fixed.

**Comment by xdave** [comment]
I'm attempting to use https://github.com/Khan/aphrodite in a project that I'm building with https://github.com/fuse-box/fuse-box

The `browser` mapping doesn't seem to work with `fuse-box` (it works for the entry point, but not the other internal modules, such as `raw`).

The only way I can make this work is by changing:

```js
var rawAsap = require("./raw");
```
to
```js
var rawAsap = require("./browser-raw");
```

in `browser-asap.js`.
